name: "Deploy to AWS"
description: "Deploy the repository to AWS EC2"
inputs:
  get-env:
    type: boolean
    default: true
    description: "Flag to get the env variables or not. Set `false` if ENV secrets should not be fetched"
  env-bucket:
    type: string
    description: "Bucket where the ENV Secrets are stored"
runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - run: chmod +x ./scripts/get_env.sh && ./scripts/get_env.sh
      shell: bash
      env:
        GET_ENV: ${{ inputs.get-env }}
        ENV_BUCKET: ${{ inputs.env-bucket }}
    - run: chmod +x ./deploy.sh && ./scripts/deploy.sh
      shell: bash
